# Generated by Django 4.1.4 on 2023-10-29 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='data/images'),
            preserve_default=False,
        ),
    ]
