# Generated by Django 4.1.4 on 2023-09-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patients',
        ),
    ]
