# Generated by Django 4.1.4 on 2023-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.CharField(default='25', max_length=3),
        ),
        migrations.AddField(
            model_name='patients',
            name='bloodGrp',
            field=models.CharField(default='A+', max_length=5),
        ),
    ]
