# Generated by Django 4.1.4 on 2023-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_age_patients_bloodgrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='img',
            field=models.ImageField(default='empty', upload_to='data/images'),
        ),
    ]
